### PR TITLE
Polish and Ukrainian translations added

### PR DESCRIPTION
**Pull request by viksok**
* Polish translations 42% ready
* Ukrainian translations 7% ready

### CODE REVIEW

**Comment by maniacx** [comment]
Hello viksok.
About Polish and ukrainian translation are they enough/complete?
Should i release them with an update?
Or should I hold and wait for more updates for polish/ukrainian translation?

**Comment by viksok** [comment]
Hi,

I still need some time to add more complicated lines to those translations. As I don't want to add fuzzy strings. So it would be better not to include them in nearest release.

Regards,
viksok



Wysłano z mojego urządzenia Galaxy



-------- Oryginalna wiadomość --------
Od: maniacx ***@***.***>
Data: 8.04.2023 00:38 (GMT+01:00)
Do: maniacx/Battery-Health-Charging ***@***.***>
DW: Viktor Sokyrko ***@***.***>, Author ***@***.***>
Temat: Re: [maniacx/Battery-Health-Charging] Polish and Ukrainian translations added (PR #15)


Hello viksok.
About Polish and ukrainian translation are they enough/complete?
Should i release them with an update?
Or should I hold and wait for more updates for polish/ukrainian translation?

**Comment by maniacx** [comment]
I was a little confused, thanks for clearing it up.

**Comment by maniacx** [comment]
If this helps
https://crowdin.com/project/battery-health-charging/invite?h=8aac1259724f76094a3d4fffd36942ff1690827

**Comment by viksok** [comment]
Hi,

amazing. this will solve the issue I had with fuzzy translations.
Crowdin suggest lot of translations. So finishing translation tasks can be done without other translators

Regards, Viktor



Wysłano z mojego urządzenia Galaxy



-------- Oryginalna wiadomość --------
Od: maniacx ***@***.***>
Data: 4.05.2023 07:46 (GMT+01:00)
Do: maniacx/Battery-Health-Charging ***@***.***>
DW: Viktor Sokyrko ***@***.***>, Author ***@***.***>
Temat: Re: [maniacx/Battery-Health-Charging] Polish and Ukrainian translations added (PR #15)


If this helps
https://crowdin.com/project/battery-health-charging/invite?h=8aac1259724f76094a3d4fffd36942ff1690827

**Comment by maniacx** [comment]
Hello Viktor. 
Yes it seems like, it has lot of translation suggestions.

One suggestion:
Whenever you complete your translation in crowdin, please download and  save a backup copy of your translation .po on your device.

I am new to crowdin and still trying to understand how it works and synchronise with GitHub.

I do not want all your hard effort of translation, get accidentally deleted if I do something wrong in crowdin or if there are some synchronization problem between GitHub and crowding due to my setup.

So you can directly  upload the backup copy of translation directly to GitHub.

**Pull request merged**
