### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by maniacx** [comment]
:)
I just used google translate and converted some translation and update. Also send it for gnome review.
What a coincidence?
I revert my translation and pull yours. Thank you.

**Comment by Vistaus** [comment]
Yes, lol. I forked your repo a few days ago to start working on the translation and finished it yesterday, when I finally had some time.

**Comment by maniacx** [comment]
Just one suggestion. The first two translations "Battery Health Charging" and "Battery Health Charging Error" are displayed on notification. 

I kept the name of the extension so that user gets informed that the notification that they are recieveing are from this extension. 

Usually other translator has left this in english and changed on the "Error" part.

I would suggest either you use english, **Battery Health Charging Foutmelding** or the equivalent dutch tranlation of the extension name for both translations.

**Comment by maniacx** [comment]
Ok. Yes My next version is not finalized yet. 
 When I complete my next version, I will update the POT file, and I will notify you here.

**Comment by Vistaus** [comment]
Hmm, I don't see the updated strings in nl.po nor in the POT file…

**Pull request merged**
