### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by ViBE-HU**
Basically it is done. First public release for version 16.

### CODE REVIEW

**Comment by maniacx** [comment]
Thank you Vibe-hu.

msgid "Battery Charging Mode" is Still English. Was it intentional?
Should it be something like "Akkumulátor töltési mód" or "Töltési mód"?
I understand you are not using Gnome 43/44 and this is not displayed in Gnome 42 panel.
Rest every thing seems good to me. Thank you. I will wait for you reply before merging.

**Comment by ViBE-HU** [comment]
no. i kept it cause it was not clear where is it appears in Ubuntu 22.04. also i thought it is the name of the plugin (like a brand) and usually i don't change names. but if you don't mind i can translate it of course. most plugins have a friendly name string (like integrating into menus) and another string for the exact plugin name (appears in notifications or credits). "Töltési mód" is correct btw. that was my original plan too.

**Comment by maniacx** [comment]
Ok. I will merge it and just add "Töltési mód" . Thank you ViBe

**Comment by ViBE-HU** [comment]
Done. You don't have to worry btw. I'm checking active project usually after 2-3 days.

**Pull request merged**
